name: unit-tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    - name: checkout repo
      uses: actions/checkout@main
    - name: run unit-tests
      run: make unit-tests
